name: jupyter
channels:
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - greenlet=3.0.2
  - icu=73.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpq=16.1
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxml2=2.12.3
  - libzlib=1.2.13
  - ncurses=6.4
  - numpy=1.26.2
  - openssl=3.2.0
  - pandas=2.1.4
  - pip=23.3.2
  - postgresql=16.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlalchemy=2.0.23
  - tk=8.6.13
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzcode=2023c
  - tzdata=2023c
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - psycopg2==2.9.9
      - pygments==2.17.2
      - rich==13.7.0
